//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UserInDate
    {
        public int userInDateId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> amperUseAmount { get; set; }
        public Nullable<double> degreesCelsius { get; set; }
    
        public virtual T_User T_User { get; set; }
    }
}
